### ISSUE TITLE
output image value range

### ISSUE THREAD

**Issue by mrymsadeghi** [Booritas/slideio#11]
When I want to read an image from czi slide and I chack the pixel values of the image:
`image = scene.read_block(rect, (int(s[0]/downrate),int(s[1]/downrate)), [0])`
`np.unique(image)`

it outputs as such:
`array([  134,   144,   152, ..., 46460, 48579, 48945], dtype=uint16)`

how can I change this to the range of 0-256? Would you please give me a hint of in what format is scene.read outputting please?

**Comment by Booritas** [comment]
SlideIO library does not perform any transformation of pixel values. It delivers values exactly as they come from the scanner. You can retrieve type of  pixel value for a channel with scene method "get_channel_data_type".
Currently normalization of data with the library is not supported. I'm working on implementation of filters that should enable such possibility but it will be available earliest in a month.
The only way I see now to scale the pixel value is to determine max pixel value and apply scaling with numpy. 
Best Regards,
Stanislav
