### ISSUE TITLE
Support .vsi (Olympus) images

### ISSUE THREAD

**Issue by mchaniotakis** [Booritas/slideio#17]
Thank for this great repo.
Are you planning to work on supporting .vsi files (Olympus)? If not, I would be willing to contribute to it with some guidance from your side.

**Comment by Booritas** [comment]
Thank you very much for your message!

I have been considering adding support for Olympus VSI slides. However, I am currently lacking testing images. If you could share some images with me or direct me to a public source of such images, I would be able to create the VSI driver as my next task. You can share links to images here or send to my private email stanislav.melnikov@gmail.com.

I am currently finishing work on a new version, which should be ready in the next couple of weeks. After that, I can shift my focus to this new task. I would be grateful for any contribution you can provide, with no obligation on your part.

Best regards,
Stanislav

**Comment by Booritas** [comment]
Support for Olympus vsi image format is added in version 2.5.0
