### ISSUE TITLE
Edit SVS auxiliary images

### ISSUE THREAD

**Issue by maferoaloaiza** [Booritas/slideio#19]
Hi, I am working with SVS images, and the label contains some confidential information that we would like to de-identify without losing all the label information since it is used for Quality Checks. The image has only one scene, and the label is only found as an auxiliary image. I can see you have transformation options at the scene level, and I was wondering if there is a way to edit and save the slide's auxiliary images as well. Thanks.

**Comment by Booritas** [comment]
Hello, SlideIO transformations do not support removing of auxiliary images. You can use SlideIO converter, which converts other formats to SVS.  But the converter recompresses the image. It takes some time. 
I hope it helps.
Best regards,
Stanislav
