### ISSUE TITLE
Can not install the version lower than 1.0.0?

### ISSUE THREAD

**Issue by tanliwei-coder** [Booritas/slideio#25]
I searched on pypi.org, found that all the version lower than 1.0.0 were deleted, why? I have a sofware which has been distributed dependend on version 0.5.225, but now can not be installed.

**Comment by Booritas** [comment]
I'm sorry to hear this. Unfortunately,  pypi services restrict storage for
packages. I had to clean the oldest versions to be able to upload the new
version. Slideio libraries should be backward compatible. You can use later
version for your software.

**Comment by tanliwei-coder** [comment]
OK, I know, it sounds that I have to release a new version for my sofware.

**Comment by Booritas** [comment]
I apologize for the problem. I did not anticipate that such old versions were still in use. In the future, I will ensure that all wheel files are preserved on GitHub. Additionally, I have submitted a request to increase storage on PyPI. The approval and duration of this request are uncertain, but I will explore alternative solutions that won't adversely affect library users. 
Please let me know if there's any way I can be of assistance.
