### ISSUE TITLE
Question: numpy >= 2.0 support

### ISSUE THREAD

**Issue by IvanKosik** [Booritas/slideio#31]
Did I understand correctly that numpy >= 2.0 is not supported at the moment?

I have tested slideio 2.5.0 and 2.6.0 with numpy 2.0.0 and numpy 2.1.0 trying to read *.svs image (using Python 3.10.14). The resulted numpy block contained all white pixels (all values are 255).
At the same time, everything works amazing with numpy 1.26.4.

**Comment by Booritas** [comment]
Thank you for your message. I'm currently refactoring the code and preparing a new version that will support NumPy 2.0 and above. I anticipate having it ready by the end of August or the beginning of September.

**Comment by Booritas** [comment]
I just released version 2.6.2, which resolves the issue and now includes support for NumPy version 2 and above.

**Comment by IvanKosik** [comment]
Thank you very much for the prompt release with this enhancement and for the great library!
Version 2.6.2 works great with NumPy >= 2.0: *.svs images are read correctly.
