### ISSUE TITLE
All channels are the same read from read_block

### ISSUE THREAD

**Issue by sandman002** [Booritas/slideio#36]
I’m reading a block from an 8-channel QPTIFF file, but the output shows the first channel repeated across all channels. What could be causing this issue?

```
slide = slideio.open_slide(qptiff_path, 'QPTIFF')
scene = slide.get_scene(0)
print(scene)
x, y = 10000, 15000
width, height = 256, 256
wsi_region_np = scene.read_block((x, y, width, height))
```

```
Name:data.qptiff
Rect: 0,0,32640,31680
Number of Channels: 8
Channel 0 data type: DT_Byte
Channel 1 data type: DT_Byte
Channel 2 data type: DT_Byte
Channel 3 data type: DT_Byte
Channel 4 data type: DT_Byte
Channel 5 data type: DT_Byte
Channel 6 data type: DT_Byte
Channel 7 data type: DT_Byte
Number of Z-Slices: 1
Number of Time Frames: 1
Z-Slice Resolution: 0
Time Frame Resolution: 0
Magnification: 10
Number of Auxiliary Images: 0
Number of Zoom Levels: 5
```

**Comment by Booritas** [comment]
Do you mean that you receive a raster with seven identical values for each pixel?
Could you try to read the channels separately? Please check if the channels are not empty (all zeros) because sometimes channels of a qptiff can have different dimensions. 
```python
wsi_channel_0 = scene.read_block((x, y, width, height), channel_indices=[0])
wsi_channel_6 = scene.read_block((x, y, width, height), channel_indices=[6])
are_identical = np.array_equal(wsi_channel_0, wsi_channel_6)
print(are_identical)
min_value = np.min(wsi_channel_0)
max_value = np.max(wsi_channel_0)
average_value = np.mean(wsi_channel_0)
print(f"Minimum: {min_value}")
print(f"Maximum: {max_value}")
print(f"Average: {average_value}")
```

**Comment by sandman002** [comment]
Yep, the data I am reading is not empty. 
Here is the output of the test above:
True
Minimum: 2
Maximum: 162
Average: 17.343563079833984

I tried reading it with tifffile package (however, slow so do not want to use it)

```python
import tifffile as tiff
import numpy as np

tif = tiff.TiffFile('./file.qptiff')

series_data = tif.series[0].asarray()

def get_crop_from_series(series, i0, j0, h, w):
    # Get the shape of the series data
    C, H, W = series.shape
    crop = series[:, i0:i0 + h, j0:j0 + w]  # Shape will be (C, h, w)
    return crop

i0, j0 = 10000, 15000  # Top-left corner of the crop (Y, X)
h, w = 512, 512  
cropped_image = get_crop_from_series(series_data, i0, j0, h, w)
print(cropped_image.shape)

wsi_channel_0 = cropped_image[0, ...]
wsi_channel_6 = cropped_image[6, ...]
are_identical = np.array_equal(wsi_channel_0, wsi_channel_6)


print(are_identical) #fault test
min_value = np.min(wsi_channel_0)
max_value = np.max(wsi_channel_0)
average_value = np.mean(wsi_channel_0)
print(f"Minimum: {min_value}")
print(f"Maximum: {max_value}")
print(f"Average: {average_value}")


```
(8, 512, 512)
False
Minimum: 2
Maximum: 162
Average: 17.343563079833984

Any help would be much appreciated.

**Comment by Booritas** [comment]
I can confirm that I am able to reproduce the issue. I will work on preparing a new version and expect it to be ready by the end of the month.

**Comment by Booritas** [comment]
I've just uploaded version 2.6.4, which includes the fix. Please let me know if it resolves the issue for you. If you're happy with the library, I'd greatly appreciate it if you could give the repository a star!

**Comment by sandman002** [comment]
Still facing the issue.
Made a quick uninstall and pip install slideio==2.6.4

**Comment by Booritas** [comment]
Would it be possible to share an image with me so I can locate the problem and fix it?

**Comment by sandman002** [comment]
Sure, how can I share it privately?

**Comment by Booritas** [comment]
You can use a service like [WeTransfer](https://wetransfer.com/) (or any other service you prefer) to send the link to my email at stanislav.melnikov@gmail.com. The service is free for files up to 2GB, and there’s no need to create an account unless you wish to.
Thank you very much!

**Comment by sandman002** [comment]
Many thanks. I just shared it.

**Comment by Booritas** [comment]
Thank you for the image. I can see the problem now. I'll try to fix it as soon as possible.

**Comment by sandman002** [comment]
Super. It is working. Thank you for your time.
