### ISSUE TITLE
Slideio is not available for Mac M1

### ISSUE THREAD

**Issue by Eisstand** [Booritas/slideio#4]
when executing
`
pip install slideio
`

it returns the error message:
`
ERROR: Could not find a version that satisfies the requirement slideio (from versions: none)
ERROR: No matching distribution found for slideio
`

pip seems to work fine otherwise

**Comment by Booritas** [comment]
Hello,
thanks for reaching me! Could you send me the following information:
- Operating system
- Python version
This will help me to identify the problem.

**Comment by Eisstand** [comment]
Certainly,
- Python 3.10.4
- macOS 12.3.1

Thank you!

**Comment by Booritas** [comment]
Ah, I see, I did not prepare macos and windows version for the python 3.10 yet. I hope I can publish them today. The latest this weekend. I will let you know when it is ready. Currently, versions for pythons 3.5 - 3.9 are published.

**Comment by Eisstand** [comment]
Fantastic! And no rush!! :)

**Comment by Booritas** [comment]
I just published library version for python 3.10 (MacOs and Windows). 
Please let me know if you have any problem with the library.
If you like the library, please consider adding a star to the repository.
Best regards,
Stanilsav

**Comment by Eisstand** [comment]
Unfortunately it still says:
`
ERROR: Could not find a version that satisfies the requirement slideio (from versions: none)
ERROR: No matching distribution found for slideio
`
I hope it's not an issue on my end, but other installing pip packages works fine... to add I am using an M1 Mac, if that's relevant

**Comment by Booritas** [comment]
Unfortunately, you're right. M1 is the problem. I don't have access to the hardware now. Neither GitLab nor GitHub support Mac Arm processors yet. I use a lot of 3rd party libraries in the project, and none of them is available for Mac Arm processor yet. I'll do some research for a solution, but it will take some time.
I'm sorry about the inconvenience. 
Best regards,
Stanislav

**Comment by aarnsygna** [comment]
Hello there,
I wanted to drop a message and mention I am experiencing the same issue, exact error message on two M1 computers.

- MacOS: 12.6.5 & 13.2.1
- Python version: 3.9.6 & 3.10.4 (Respectively)

As is already confirmed it is an architecture issue, I did want to add on an Intel Mac (python 3.10.x) issue does not occur. (Though python 3.11 also caused similar issue, but more of a fyi). 

Any suggestions or anything I can provide?

**Comment by bhanudaybirla** [comment]
Hi @Booritas , I am also facing the same issues mentioned here in this thread. I too have Mac with M1 chip and i think because of that I am not able to install. Is there an update on this or any workaround till we get pip install working for slideio. 
Also can we build using raw git repo on mac with M1 chip?

**Comment by Booritas** [comment]
Hello, I'm sorry for the inconvenience. I have some problems with M1/M2 chips - I don't have the hardware and Github and Jfrog which I use for CI, do not support the platform. But I have some idea and will try to solve the problem. Give me a few days to try something. 
@bhanudaybirla, yes you can build the library from the repository. The instructions are here: https://www.slideio.com/python.html.
Best regards,
Stanislav

**Comment by bhanudaybirla** [comment]
Thank you very much. Looking forward to the fix you are working on. I will also try building it from repo.

**Comment by Lezgo11** [comment]
Hey there! I am having this same issue with a windows PC. I don't understand how to build the library from the repository from the instructions.

**Comment by Booritas** [comment]
Hello @Lezgo11, 
you should not have any problem with the Windows version unless it runs on an arm processor. Could you give some details about your environment:
- OS version
- Processor (arm/x86_64)
- Python version
Best regards,
Stanislav

**Comment by Booritas** [comment]
Dear @Lezgo11,
Unfortunately, the latest Windows version of the library is available for pythons 3.6-3.10. I'm preparing a new version that should fix this issue as well as packages for MacOS arm machines. I expect it to be ready in 1-2 weeks. Would it be possible to work with python 3.10 until this time?
I'm sorry for any inconvenience,
Stanislav

**Comment by Lezgo11** [comment]
For sure! Silly me. Thank you!

**Comment by Booritas** [comment]
Hello,

I have managed to compile a version for MacOS M1/M2 processors. Unfortunately, I cannot run a complete test on the package due to a lack of hardware. Please try it and let me know if it works. You can download the wheel files from the GitLab repository https://gitlab.com/bioslide/pythons. Select a wheel file according to your Python version and run the pip utility. For Python 3.11, it should be:

```bash
python3 -m pip install ./pythons/slideio-2.0.9-cp311-cp311-macosx_11_0_arm64.whl
```
Please let me know if it works so that I can make the package publicly available. If you like the library, please consider giving a star to the slideio repository.
Best regards,
Stanislav

**Comment by Booritas** [comment]
MacOS ARM version is public now.
