### ISSUE TITLE
Leaking Memory on Windows

### ISSUE THREAD

**Issue by s1910458007** [Booritas/slideio#6]
Hi, could it be possible, that the problem with memory leaks from issue #1  (that was fixed for linux) is still present for windows?
I have exactly the same behaviour as described in the issue.
Could you please check the latest version?
thanks in advance!

**Comment by Booritas** [comment]
Hello,
thanks a lot for your message. I'll check the issue again. Unfortunately, some leaks may appear only for specific images. It may depend on internal structure, compression, etc. More information would help to localize the problem. Important are:
- image type;
- image size;
- compression.
It would be very useful if you can share an image that causes the problem.
Best Regards,
Stanislav

**Comment by s1910458007** [comment]
Hello again, thank you for the quick reply!

of course, here you are:

- image type: **svs file from an aperio scanner**

- image size: **55800  x 26031 pixels (RGB)**

- compression: **JPEG using libjpeg**

you can download a zip file that contains the svs file via the following link:
https://drive.google.com/file/d/17f2vuQUjjsANVaxoHeCUM4YB-JutQuiY/view?usp=sharing

just for the case that you are interested in the hardware i am using:
- Device name: LAPTOP-SNKHH2A3
- Processor: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz 2.59 GHz
- Installed RAM: 16.0 GB (15.9 GB usable)
- System type: 64-bit operating system, x64-based processor
- Operation system: Windows 11 Pro (Version 21H2)

Please let me know if you need any further information (source code, detailed description, ...) 

Best Regards,
Daniel :)

**Comment by Booritas** [comment]
Hi Daniel,
Thanks for the image. Now I have everything for the investigation of the problem!
Best regards,
Stanislav

**Comment by Booritas** [comment]
Hi again,
Could you send me a code snippet how do you work with the image? A direct test (opening the image and reading of a region) does not show any memory leak.
Thanks,
Stanislav

**Comment by s1910458007** [comment]
Hello Stanislav,
because of your last message I doublechecked my problem once again in more detail.
You are absolutely right, the slideio library is **not** the cause of my problem!
Something else allocated most of my memory, and for that reason the **scene.read_block()** did not work properly any more 
(seems like scene.read_block() needs a remarkable amount of free RAM, otherwise the runtime increases dramatically).
Sorry to trouble you and thank you for excellent service!
best regards Daniel

**Comment by Booritas** [comment]
Hi Daniel,
thanks for the message and sorry for the delay with the answer. Normally, read_block should not require a lot of memory, unless you read a really large image block in the original resolution. If you read only a part of an image or don't need high resolution, the function should not allocate much more memory than the requested region requires. 
You can check the [tutorial](http://slideio.com/tutorial.html#read-a-rectangular-block-with-rescaling) how to read a region with rescaling.
I hope it helps,
Best Regards ,
Stanislav
