### ISSUE TITLE
Support for slides with more than three channels

### ISSUE THREAD

**Issue by robinglord1** [Booritas/slideio#8]
Hello,
Does slideio support images with an arbitrary number of channels? I'm expecting to work with immunofluorescent images that can sometimes have more than three channels.
Thank you for the answer!

**Comment by Booritas** [comment]
Hello,
yes, the library supports arbitrary number of channels. It is as well tested against immunofluorescent images.
Best regards,
Stanislav

**Comment by robinglord1** [comment]
Great, thank you for the quick answer!
